# Generated by Django 2.2 on 2019-08-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://www.caratlane.com/blog/wp-content/uploads/2017/04/Block-Post.jpg', upload_to=''),
        ),
    ]
