# Generated by Django 2.2 on 2019-07-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190624_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='product',
            name='caliber',
            field=models.CharField(choices=[('18', '18'), ('21', '21')], default='21', max_length=2),
        ),
    ]
